language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - jruby-9.2.6.0
gemfile:
  - gemfiles/ar60.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.2.6.0
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
env:
  global:
    - PGHOST=""
    - PGPORT=5432
before_script:
  - psql -U postgres -c "create database postgis_adapter_test"
  - psql -U postgres -d postgis_adapter_test -c "create extension postgis"
script: bundle exec rake test
